#!/bin/bash

# Cocoon Paraphrase - YAML Workflow Encoder
# Compresses and encodes YAML files into a portable base64 string
# Usage: ./paraphrase.sh [directory]

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the target directory (default to current directory)
TARGET_DIR="${1:-.}"

echo -e "${BLUE}Cocoon Paraphrase - YAML Workflow Encoder${NC}"
echo -e "${BLUE}==========================================${NC}"
echo ""

# Check if directory exists
if [ ! -d "$TARGET_DIR" ]; then
    echo -e "${RED}Error: Directory '$TARGET_DIR' does not exist${NC}"
    exit 1
fi

# Change to target directory
cd "$TARGET_DIR"
WORKING_DIR=$(pwd)

echo -e "${YELLOW}Scanning directory: ${WORKING_DIR}${NC}"
echo ""

# Find all YAML files
YAML_FILES=$(find . -type f \( -name "*.yaml" -o -name "*.yml" \) | sort)

if [ -z "$YAML_FILES" ]; then
    echo -e "${RED}Error: No YAML files found in directory${NC}"
    exit 1
fi

# Count files
FILE_COUNT=$(echo "$YAML_FILES" | wc -l)
echo -e "${GREEN}Found ${FILE_COUNT} YAML file(s)${NC}"
echo ""

# Generate the reconstruction script
TEMP_SCRIPT=$(mktemp)

cat > "$TEMP_SCRIPT" << 'SCRIPT_HEADER'
#!/bin/bash

# Cocoon Workflow Structure Setup Script
# Generated by Cocoon Paraphrase

set -e  # Exit on any error

echo "Creating workflow structure..."
echo ""

SCRIPT_HEADER

# Process each YAML file
echo "$YAML_FILES" | while IFS= read -r file; do
    # Remove leading ./
    clean_path="${file#./}"
    
    # Get directory path (if any)
    dir_path=$(dirname "$clean_path")
    
    # Create directory if needed (skip if it's just ".")
    if [ "$dir_path" != "." ]; then
        echo "mkdir -p \"$dir_path\"" >> "$TEMP_SCRIPT"
    fi
    
    # Add file creation with heredoc
    echo "cat > \"$clean_path\" << 'EOF'" >> "$TEMP_SCRIPT"
    cat "$file" >> "$TEMP_SCRIPT"
    # Ensure newline before EOF marker to prevent heredoc syntax errors
    [ -n "$(tail -c 1 "$file")" ] && echo "" >> "$TEMP_SCRIPT"
    echo "EOF" >> "$TEMP_SCRIPT"
    
    echo -e "${GREEN}  ✓${NC} Encoded: $clean_path"
done

# Add completion message to script
cat >> "$TEMP_SCRIPT" << 'SCRIPT_FOOTER'

echo ""
echo "✓ Workflow structure created successfully!"
echo "Run 'cocoon main.yaml' to execute your workflow."
SCRIPT_FOOTER

echo ""
echo -e "${YELLOW}Generating base64 paraphrase...${NC}"
echo ""

# Base64 encode the script
BASE64_OUTPUT=$(base64 -w 0 < "$TEMP_SCRIPT")

# Calculate size
ORIGINAL_SIZE=$(du -sh "$WORKING_DIR" | cut -f1)
ENCODED_SIZE=${#BASE64_OUTPUT}

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Paraphrase Generated Successfully!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${BLUE}Original Size:${NC} $ORIGINAL_SIZE"
echo -e "${BLUE}Encoded Size:${NC} $ENCODED_SIZE characters"
echo ""
echo -e "${YELLOW}Copy the following base64 string:${NC}"
echo ""
echo "----------------------------------------"
echo "$BASE64_OUTPUT"
echo "----------------------------------------"
echo ""
echo -e "${BLUE}To recreate this workflow on another machine:${NC}"
echo ""
echo -e "  ${GREEN}echo \"$BASE64_OUTPUT\" | base64 -d | bash${NC}"
echo ""
echo -e "${BLUE}Or save to a variable and use later:${NC}"
echo ""
echo -e "  ${GREEN}WORKFLOW=\"$BASE64_OUTPUT\"${NC}"
echo -e "  ${GREEN}echo \"\$WORKFLOW\" | base64 -d | bash${NC}"
echo ""
echo -e "${BLUE}Or download and execute directly:${NC}"
echo ""
echo -e "  ${GREEN}curl -sSL https://raw.githubusercontent.com/DebalGhosh100/blocks/paraphrase/examples/paraphrase-strings/YOUR_WORKFLOW.txt | base64 -d | bash${NC}"
echo ""

# Clean up
rm -f "$TEMP_SCRIPT"

echo -e "${YELLOW}Tip: Save this base64 string to share your workflow configuration${NC}"
